
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.233.45.84:3306/pigs_blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: pigs_blog
    password: '123456'
#  redis:
#    host: 101.43.47.172
#    port: 6379
#  cache:
#    redis:
#      time-to-live: 1800000  # 失效时间——毫秒（30分钟）



server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml
