spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pigs_blog?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC&useSSL=false
    username: root
    password: '123456'

  security:
    oauth2:
      client:
        registration:
          github:
            #对应Github账号配置的Client ID
            client-id: Iv1.984c8b90481dcebc
            #对应Github账号配置的Client secrets
            client-secret: b1d22019afa34b206e214d0d5431098a23bec22f

  redis:
    host: 49.233.45.84
    password: 123123
    port: 6379
    timeout: 5000
    ssl: false

server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/*/*.xml


logging:
  config: classpath:logback-spring.xml

github:
  oauth:
    clientid: Iv1.984c8b90481dcebc
    clientsecret: b1d22019afa34b206e214d0d5431098a23bec22f
    callback: http://localhost:8081/github/callback



